# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oplus/ossi/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/oplus/ossi

PRODUCT_COPY_FILES += \
    vendor/oplus/ossi/proprietary/boot/ramdisk/vendor/app/mcRegistry/020f0000000000000000000000000000.drbin:$(TARGET_COPY_OUT_SYSTEM)/boot/ramdisk/vendor/app/mcRegistry/020f0000000000000000000000000000.drbin \
    vendor/oplus/ossi/proprietary/boot/ramdisk/vendor/app/mcRegistry/020f0000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_SYSTEM)/boot/ramdisk/vendor/app/mcRegistry/020f0000000000000000000000000000.tlbin \
    vendor/oplus/ossi/proprietary/boot/ramdisk/vendor/app/mcRegistry/05120000000000000000000000000000.drbin:$(TARGET_COPY_OUT_SYSTEM)/boot/ramdisk/vendor/app/mcRegistry/05120000000000000000000000000000.drbin \
    vendor/oplus/ossi/proprietary/boot/ramdisk/vendor/app/mcRegistry/05120000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_SYSTEM)/boot/ramdisk/vendor/app/mcRegistry/05120000000000000000000000000000.tlbin \
    vendor/oplus/ossi/proprietary/boot/ramdisk/vendor/app/mcRegistry/05120000000000000000000000000001.drbin:$(TARGET_COPY_OUT_SYSTEM)/boot/ramdisk/vendor/app/mcRegistry/05120000000000000000000000000001.drbin \
    vendor/oplus/ossi/proprietary/boot/ramdisk/vendor/app/mcRegistry/05120000000000000000000000000001.tlbin:$(TARGET_COPY_OUT_SYSTEM)/boot/ramdisk/vendor/app/mcRegistry/05120000000000000000000000000001.tlbin \
    vendor/oplus/ossi/proprietary/boot/ramdisk/vendor/app/mcRegistry/06090000000000000000000000000000.drbin:$(TARGET_COPY_OUT_SYSTEM)/boot/ramdisk/vendor/app/mcRegistry/06090000000000000000000000000000.drbin \
    vendor/oplus/ossi/proprietary/boot/ramdisk/vendor/app/mcRegistry/06090000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_SYSTEM)/boot/ramdisk/vendor/app/mcRegistry/06090000000000000000000000000000.tlbin \
    vendor/oplus/ossi/proprietary/boot/ramdisk/vendor/app/mcRegistry/0706000000000000000000000000004d.tlbin:$(TARGET_COPY_OUT_SYSTEM)/boot/ramdisk/vendor/app/mcRegistry/0706000000000000000000000000004d.tlbin \
    vendor/oplus/ossi/proprietary/boot/ramdisk/vendor/app/mcRegistry/07061000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_SYSTEM)/boot/ramdisk/vendor/app/mcRegistry/07061000000000000000000000000000.tlbin \
    vendor/oplus/ossi/proprietary/boot/ramdisk/vendor/app/mcRegistry/07150000000000000000000000000000.drbin:$(TARGET_COPY_OUT_SYSTEM)/boot/ramdisk/vendor/app/mcRegistry/07150000000000000000000000000000.drbin \
    vendor/oplus/ossi/proprietary/boot/ramdisk/vendor/app/mcRegistry/07150000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_SYSTEM)/boot/ramdisk/vendor/app/mcRegistry/07150000000000000000000000000000.tlbin \
    vendor/oplus/ossi/proprietary/boot/ramdisk/vendor/app/mcRegistry/07170000000000000000000000000000.drbin:$(TARGET_COPY_OUT_SYSTEM)/boot/ramdisk/vendor/app/mcRegistry/07170000000000000000000000000000.drbin \
    vendor/oplus/ossi/proprietary/boot/ramdisk/vendor/app/mcRegistry/07170000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_SYSTEM)/boot/ramdisk/vendor/app/mcRegistry/07170000000000000000000000000000.tlbin \
    vendor/oplus/ossi/proprietary/boot/ramdisk/vendor/app/mcRegistry/08030000000000000000000000000000.tabin:$(TARGET_COPY_OUT_SYSTEM)/boot/ramdisk/vendor/app/mcRegistry/08030000000000000000000000000000.tabin \
    vendor/oplus/ossi/proprietary/boot/ramdisk/vendor/app/mcRegistry/08040000000000000000000000003419.tabin:$(TARGET_COPY_OUT_SYSTEM)/boot/ramdisk/vendor/app/mcRegistry/08040000000000000000000000003419.tabin \
    vendor/oplus/ossi/proprietary/boot/ramdisk/vendor/app/mcRegistry/08050000000000000000000000003419.drbin:$(TARGET_COPY_OUT_SYSTEM)/boot/ramdisk/vendor/app/mcRegistry/08050000000000000000000000003419.drbin \
    vendor/oplus/ossi/proprietary/boot/ramdisk/vendor/app/mcRegistry/08050000000000000000000000003419.tlbin:$(TARGET_COPY_OUT_SYSTEM)/boot/ramdisk/vendor/app/mcRegistry/08050000000000000000000000003419.tlbin \
    vendor/oplus/ossi/proprietary/boot/ramdisk/vendor/app/mcRegistry/08110000000000000000000000000000.tabin:$(TARGET_COPY_OUT_SYSTEM)/boot/ramdisk/vendor/app/mcRegistry/08110000000000000000000000000000.tabin \
    vendor/oplus/ossi/proprietary/boot/ramdisk/vendor/app/mcRegistry/40188311faf343488db888ad39496f9a.drbin:$(TARGET_COPY_OUT_SYSTEM)/boot/ramdisk/vendor/app/mcRegistry/40188311faf343488db888ad39496f9a.drbin \
    vendor/oplus/ossi/proprietary/boot/ramdisk/vendor/app/mcRegistry/40188311faf343488db888ad39496f9a.tlbin:$(TARGET_COPY_OUT_SYSTEM)/boot/ramdisk/vendor/app/mcRegistry/40188311faf343488db888ad39496f9a.tlbin \
    vendor/oplus/ossi/proprietary/boot/ramdisk/vendor/app/mcRegistry/5020170115e016302017012521300000.drbin:$(TARGET_COPY_OUT_SYSTEM)/boot/ramdisk/vendor/app/mcRegistry/5020170115e016302017012521300000.drbin \
    vendor/oplus/ossi/proprietary/boot/ramdisk/vendor/app/mcRegistry/5020170115e016302017012521300000.tlbin:$(TARGET_COPY_OUT_SYSTEM)/boot/ramdisk/vendor/app/mcRegistry/5020170115e016302017012521300000.tlbin \
    vendor/oplus/ossi/proprietary/boot/ramdisk/vendor/app/mcRegistry/abcd270ea5c44c58bcd3384a2fa2539e.tabin:$(TARGET_COPY_OUT_SYSTEM)/boot/ramdisk/vendor/app/mcRegistry/abcd270ea5c44c58bcd3384a2fa2539e.tabin \
    vendor/oplus/ossi/proprietary/boot/ramdisk/vendor/app/mcRegistry/e97c270ea5c44c58bcd3384a2fa2539e.tabin:$(TARGET_COPY_OUT_SYSTEM)/boot/ramdisk/vendor/app/mcRegistry/e97c270ea5c44c58bcd3384a2fa2539e.tabin \
    vendor/oplus/ossi/proprietary/boot/ramdisk/vendor/bin/mcDriverDaemon:$(TARGET_COPY_OUT_SYSTEM)/boot/ramdisk/vendor/bin/mcDriverDaemon \
    vendor/oplus/ossi/proprietary/boot/ramdisk/vendor/bin/vndservice:$(TARGET_COPY_OUT_SYSTEM)/boot/ramdisk/vendor/bin/vndservice \
    vendor/oplus/ossi/proprietary/boot/ramdisk/vendor/bin/vndservicemanager:$(TARGET_COPY_OUT_SYSTEM)/boot/ramdisk/vendor/bin/vndservicemanager \
    vendor/oplus/ossi/proprietary/boot/ramdisk/vendor/build.prop:$(TARGET_COPY_OUT_SYSTEM)/boot/ramdisk/vendor/build.prop
